[general]
import = [
"~/.config/alacritty/alacritty-theme/themes/dracula-soft.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
option_as_alt = "Both"

# dimensions = { columns = 100, lines = 28 }
dimensions = { columns = 150, lines = 41 }
position = { x = 0, y = 0 }

decorations = "Buttonless"
# decorations = "transparent"

# opacit = 0.8
# blur = true

[colors]
[colors.primary]
# foreground = "#000408"
# background = "#0c011c"  # purple
# background = "#0b121a"  # dark blue

[font]
normal.family = "JetBrainsMono NF"
# normal.family = "Firacode Nerd Font"
# normal.style = "Regular"
offset = { x = 1, y = 2 }
size = 14

[keyboard]
bindings = [
{ key = "N", mods = "Super", action = "CreateNewWindow" },
]
